// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCMS.Infrastructure;

#nullable disable

namespace SCMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250923024322_AddMissingUserRoles")]
    partial class AddMissingUserRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCMS.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Món chính"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Đồ uống"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Món ăn vặt"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Chưa phân loại"
                        });
                });

            modelBuilder.Entity("SCMS.Domain.MenuItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("SCMS.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SCMS.Domain.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtTimeOfOrder")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SCMS.Domain.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("SCMS.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Student"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "CanteenStaff"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "CanteenManager"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "SystemAdmin"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Parent"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "HeadTeacher"
                        },
                        new
                        {
                            RoleId = 7,
                            RoleName = "SchoolAdministration"
                        });
                });

            modelBuilder.Entity("SCMS.Domain.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SCMS.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HeadTeacherId")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("HeadTeacherId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 9, 23, 2, 43, 20, 518, DateTimeKind.Utc).AddTicks(3568),
                            Email = "admin@scms.com",
                            FullName = "System Administrator",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$dWg.91rdTRYexs7zc40PduWl0PQG91QRir/xTkLbZl2hXF6qQIB4m",
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 9, 23, 2, 43, 20, 678, DateTimeKind.Utc).AddTicks(6234),
                            Email = "canteenmanager@scms.com",
                            FullName = "Canteen Manager",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$DY7KTpQrZqssG0QFgtp4xOXFWg9sDoE3vIUVKVPN8Tc94C15G/ZuS",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2025, 9, 23, 2, 43, 20, 830, DateTimeKind.Utc).AddTicks(1937),
                            Email = "student@scms.com",
                            FullName = "Nhat Dung",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$4CNifz1JvU0JD4Y1z4EVXe0k6qUeUEomc5nodun4z4EictkpYemsC",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2025, 9, 23, 2, 43, 20, 984, DateTimeKind.Utc).AddTicks(9520),
                            Email = "staff@scms.com",
                            FullName = "Thien Truong",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$fBFPCHo8d2FZR6K3XZOGp.v5MAqeEiHbBnS3hcB2AGyMURat8/zJq",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 15,
                            CreatedAt = new DateTime(2025, 9, 23, 2, 43, 21, 137, DateTimeKind.Utc).AddTicks(8296),
                            Email = "parent@scms.com",
                            FullName = "Default Parent",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$9JrsOCTfEueoTjymy.G/jOdRkaJUFlcLP1pZx6i/cPCf.RKHXSwfq",
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 16,
                            CreatedAt = new DateTime(2025, 9, 23, 2, 43, 21, 274, DateTimeKind.Utc).AddTicks(1409),
                            Email = "headteacher@scms.com",
                            FullName = "Default Head Teacher",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$zUUWsdg3ERIG.WLy3HAVdefaMzdipHBMDliRHS3CXGFx5dZqTxMXu",
                            RoleId = 6
                        },
                        new
                        {
                            UserId = 17,
                            CreatedAt = new DateTime(2025, 9, 23, 2, 43, 21, 411, DateTimeKind.Utc).AddTicks(4693),
                            Email = "schooladmin@scms.com",
                            FullName = "School Admin User",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$RCpsBHVAMT.dMgVk46031.Rqth7Y4XVMmiyenJ6THKdzMYbg1O9LS",
                            RoleId = 7
                        });
                });

            modelBuilder.Entity("SCMS.Domain.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("SCMS.Domain.MenuItem", b =>
                {
                    b.HasOne("SCMS.Domain.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SCMS.Domain.Order", b =>
                {
                    b.HasOne("SCMS.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCMS.Domain.OrderItem", b =>
                {
                    b.HasOne("SCMS.Domain.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCMS.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SCMS.Domain.Transaction", b =>
                {
                    b.HasOne("SCMS.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("SCMS.Domain.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SCMS.Domain.User", b =>
                {
                    b.HasOne("SCMS.Domain.User", "HeadTeacher")
                        .WithMany()
                        .HasForeignKey("HeadTeacherId");

                    b.HasOne("SCMS.Domain.User", "Parent")
                        .WithMany("LinkedStudents")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SCMS.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadTeacher");

                    b.Navigation("Parent");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SCMS.Domain.Wallet", b =>
                {
                    b.HasOne("SCMS.Domain.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("SCMS.Domain.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCMS.Domain.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("SCMS.Domain.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SCMS.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SCMS.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SCMS.Domain.User", b =>
                {
                    b.Navigation("LinkedStudents");

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
